server:
  port: 8080

#Need this here and in bootstrap.yml
spring:
  application:
    name: gordonfrog
  #datasource:
    #url: jdbc:mysql://mysql:3306/gordonfrog
  autoconfigure:
    exclud: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: gordonfrog # Database name.
      uri: mongodb://mongodb:27017/gordonfrog # Mongo database URI. When set, host and port are ignored.
      #username: 
      #password

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true