server:
  port: 8080

#Need this here and in bootstrap.yml
spring:
  application:
    name: gordonfrog

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true